# Generated by Django 3.2.15 on 2023-01-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cccomplete',
            new_name='complete',
        ),
    ]
